mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.94.229.157:3306/database
      username: root
      password: Ma123456789!
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
        mode: HTML5
  mvc:
     static-path-pattern: /static/**
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
     com.neuedu.dao: debug



#  pagehelper.helper-dialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.support-methods-arguments=true
#  pagehelper.params=countSql