package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    //根据用户i和商品id查询购物信息
    Cart findCartByUseridAndProductId(@Param("userid") Integer userid,@Param("productId") Integer productId);
/**
        * This method was generated by MyBatis Generator.
 * This method corresponds to the database table neuedu_cart
 *
         * @mbg.generated
 */
    int updateByPrimaryKey(Cart record);


    /**
     * 查询用户的购物车信息
     * */
    List<Cart> findCartsByUserid(@Param("userid") Integer userid);

    /**
     *
     *统计用户购物车中未选中的商品的数量
     */

    Integer  isAllChecked(@Param("userid") Integer userid);


    //查看用户已勾选的商品

    List<Cart> findCartsByUseridAndChecked(@Param("userId") Integer userId);


    //清空购物车中已选中的商品


    int deleteBatch(@Param("cartList") List<Cart> cartList);
}