package com.neuedu.dao;

import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();
    int updateByPrimaryKey(Product record);
    int deleteByPrimaryKey(Integer id);
    Product selectByPrimaryKey(Integer id);
    List<Product> findProductsByNameAndId(@Param("productId")Integer productId,
                                          @Param("productName")String productName);

    /**
     * 扣库存
     * */
    int  reduceProductStock(@Param("productId") Integer productId,@Param("stock") Integer stock);

}